-- Lock the Supabase Data API. The Next.js app uses DATABASE_URL as the
-- table owner, which bypasses RLS, so pages and sync keep working.
-- No policies on purpose: anon/authenticated see zero rows.
ALTER TABLE "amendments" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "api_usage" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "bill_actions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "bill_classifications" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "bill_committee_referrals" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "bill_documents" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "bill_sponsors" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "bill_topics" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "bills" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "classification_overrides" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "committees" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "event_bills" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "event_topics" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "events" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "individual_votes" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "people" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "r2_objects" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "related_bills" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "roll_calls" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "sessions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "supplements" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "sync_runs" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "topics" ENABLE ROW LEVEL SECURITY;
